name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ contains(env.COMMIT_MESSAGES, '#skip') == false }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "poke-ci-test"
          heroku_email: "rafael.tragueta79@gmail.com"
          healthcheck: "https://poke-ci-test.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ' ') }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: success() # Pick up events even if the job fails or is canceled.
  bump_version:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        # Might want to use instead of version to be granted @eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        # see: https://fullstackopen.com/en/part11/keeping_green#a-note-about-using-third-party-actions
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ contains(env.COMMIT_MESSAGES, '#skip') == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ' ') }}
