name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ' ') }}
        if: ${{ contains(env.COMMIT_MESSAGES, '#skip') == true }}
        run: echo "$COMMIT_MESSAGES"
